### ISSUE TITLE
can-component gives deprecated warning about using template

### ISSUE THREAD

**Issue by BigAB** [icanjs/auth-component#16]
When using the latst can-component, you get this deprecated warning in the console:

![image](https://cloud.githubusercontent.com/assets/76821/20635569/600755ce-b324-11e6-9001-6436bc4c02e1.png)
 > can-component.prototype.template: is deprecated and will be removed in a future release. Use can-component.prototype.view

**Comment by marshallswain** [comment]
Issue moved to [icanjs/can-auth-component #1](https://github.com/icanjs/can-auth-component/issues/1) via [**ZenHub**](https://www.zenhub.com/)
